---
- name: install python
  yum: name={{ item }} state=present
  with_items:
    - python27-devel
    - python27-libs
    - python27-pip
    - python27-wheel
    - python27-tools
    - python27-lxml
    - python27-setuptools
  when: "'python27' in languages"

- name: copy virtualenv setting file
  copy:
    src=virtualenv.sh
    dest=/etc/profile.d/virtualenv.sh
  when: "'python27' in languages"

- name: install and update virtualenv
  pip: name={{ item }} state=latest
  with_items:
    - virtualenv
    - virtualenvwrapper
  when: "'python27' in languages"
