# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
IP_ADDR = "192.168.33.32"
PROJECTNAME = "test"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-65"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  config.vm.network :private_network, ip: IP_ADDR
  config.vm.hostname = PROJECTNAME

  config.vm.network :forwarded_port, guest: 8082, host: 8082

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook  = "bootstrap.yml"
    ansible.verbose = "vvvv"
    ansible.inventory_path  = "hosts"
    ansible.limit = 'all'
  end
end
