---
- name: install go
  yum: name={{ item }} state=present
  with_items:
    - mercurial
    - golang
  when: "'go' in languages"

- name: mkdir working directory for go
  sudo: no
  file:
    path={{ go_path }}/src
    state=directory
    owner={{ user }}
    group={{ user }}
  when: "'go' in languages"

- name: copy setting file
  template:
    src=go.sh.j2
    dest=/etc/profile.d/go.sh
  when: "'go' in languages"
