---
- name: install java
  yum: name={{ item }} state=present
  with_items:
    - java-1.7.0-openjdk

- name: get maven repo
  get_url:
    url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
    dest=/etc/yum.repos.d/epel-apache-maven.repo

- name: install maven
  yum: name={{ item }} state=present
  with_items:
    - apache-maven
