---
- name: install mysql from mysql-community
  yum: name={{ item }} state=present enablerepo=mysql56-community
  with_items:
    - mysql-server
    - mysql-devel
  notify:
    - mysql start

- name: install python client of mysql
  yum: name=MySQL-python state=present
  when: "'python' in languages"
