---
- name: create the repository for td-agent
  copy: src=td-agent.repo dest=/etc/yum.repos.d/td-agent.repo mode=0644

- name: install td-agent
  yum: name=td-agent enablerepo=treasuredata

- name: make conf directory
  file:
    path=/etc/td-agent/conf.d
    state=directory
    mode=0644

- name: configure file of td-agent
  template:
    src=td-agent.conf.j2
    dest=/etc/td-agent/td-agent.conf
  notify: start td-agent
